version: "3.8"

services:

  db:
    container_name: postgresql_db
    image: postgres:14.7-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_lms

  app:
    container_name: app
    build: .
    environment:
      ASYNC_SQLALCHEMY_DATABASE_URL: postgresql+asyncpg://postgres:password@db/fastapi_lms
      SQLALCHEMY_DATABASE_URL: postgresql+psycopg2://postgres:password@db/fastapi_lms
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
